version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_startkit
    container_name: laravel_startkit
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    depends_on:
      - app
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
